alias v="vim"
alias vimedit="vim ~/.vimrc"
alias pull="git pull"
alias push="git push"
alias f="find  -not -iwholename '*.svn*' -iname "
alias pu="phpunit --colors"
alias eg="egrep -irn --exclude-dir=\".svn\" --color=auto"
alias ff="fg"
alias jj="jobs"
alias ..="cd .."
alias c="clear"
alias untar="tar xzvf"
alias gitedit="vim ~/.gitconfig"
alias l="ls"
alias la="ls-lah"
alias du="du -hs"

